name: 'Blog Post Workflow'
author: 'Gautam Krishna R'
description: 'Allows you to show your latest blog posts on your github profile or project readme'

inputs:
  gh_token:
    description: 'GitHub access token with Repo scope'
    required: false
    default: ${{ github.token }}
  readme_path:
    description: 'Comma separated paths of the readme files you want to update'
    default: './README.md'
    required: false
  max_post_count:
    description: 'Maximum number of posts you want to show on your readme, all feeds combined'
    default: '3'
    required: false
  feed_list:
    description: "Comma separated list of RSS feed urls"
    default: "https://www.linkedin.com/in/blai-muñoz-mateu/recent-activity/"
    required: true
  tag_post_pre_newline:
    description: "Inserts newline before the closing tag and after the opening tag when using the template option, for formatting"
    required: false
  template:
    description: "Template to use while creating the list of posts. It can contain $title,$url, $newline and $date as variables"
    default: "default"
    required: false
  date_format:
    description: "Allows you to change the format of the date or time displayed when using the $date in the template option"
    default: "UTC:ddd mmm dd yyyy h:MM TT"
    required: false
  commit_message:
    description: "Commit message used while committing to the repo"
    default: "Updated with the latest blog posts"
    required: false
  committer_username:
    description: "Username used while committing to the repo"
    default: "blog-post-bot"
    required: false
  feed_names:
    description: "Comma separated name of the feeds to show on template"
    default: "LinkedIn"
    required: false
outputs:
  results:
    description: "JSON stringified array of posts"

runs:
  using: node16
  main: dist/blog-post-workflow.js
branding:
  icon: 'activity'
  color: 'blue'
