name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Update README with latest blog posts
        uses: blaimuma/blaimunozmateu@main
        with:
          feed_list: "https://www.linkedin.com/in/blai-muñoz-mateu/recent-activity/"
